# Aliases are short commands to replace long ones.

alias crossbuild='~/900RobotCode/zebROS_ws/cross_build.sh'
alias deploy='~/900RobotCode/scripts/deploy.sh'
alias diaglaunch='echo "Not implmented yet! Check command_aliases.sh"'
alias hwlaunch='roslaunch controller_node 2026_compbot_combined.launch'
alias killros='~/900RobotCode/zebROS_ws/kill_ros_.sh'
alias natbuild='~/900RobotCode/zebROS_ws/native_build.sh'
alias rosjet='source ~/900RobotCode/zebROS_ws/ROSJetsonMaster.sh'
alias rosstd='source ~/900RobotCode/zebROS_ws/ROSStandard.sh'
alias simlaunch='roslaunch controller_node 2026_compbot_combined.launch hw_or_sim:=sim'
alias fieldsim='roslaunch controller_node 2026_compbot_combined.launch hw_or_sim:=sim stage_sim:=true'
alias ls='ls --color'
alias driversim='rqt --standalone rqt_driver_station_sim'
alias axclient='rosrun actionlib_tools axclient.py'
alias ddr='rosrun rqt_reconfigure rqt_reconfigure'
alias plotjuggler='roslaunch plotjuggler_ros plotjuggler.launch'
